import type { Metadata } from "next";
import {siteUrl,businessSchema,serviceArea,seoTitle,seoDescription} from "@/lib/seo";
import { asset, site } from "@/lib/site";
import EnquiryForm from "@/components/EnquiryForm";
export const metadata: Metadata = { alternates: { canonical: "/" }, openGraph: { url: siteUrl, type: "website", siteName: "Goodboys", locale: "en_GB", title: seoTitle, description: seoDescription, images: [{url:"/images/hero.jpg",width:360,height:450,alt:"Happy dog exploring outdoors with Goodboys"}] } };
export default function Home() { return <>
<a className="skip" href="#main">Skip to content</a>
<header><a href="#" aria-label="Goodboys home"><img className="logo" src="/images/logo.png" alt="Goodboys"/></a><nav aria-label="Main navigation"><a href="#walks">The walks</a><a href="#about">Our kind of care</a><a href="#faq">FAQs</a></nav><a className="button small" href="#join">Join the gang ↗</a></header>
<main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(businessSchema()).replace(/</g,"\\u003c")}}/><section className="hero"><div className="hero-copy"><span className="eyebrow">DOG WALKING & GOOD COMPANY</span><h1>Good walks.<br/>Great dogs.</h1><p>More sniffing. More exploring.<br/>More of what makes their tail wag.{serviceArea&&<><br/><span className="hero-area">Dog walking in {serviceArea}.</span></>}</p><a className="button" href="#join">Find your dog’s happy place ↗</a><div className="hero-note"><span className="spark">✳</span><span>For the muddy paws.<br/>And the good souls attached.</span></div></div><div className="hero-photo"><img src={asset("hero.jpg")} width={360} height={450} alt="Happy dog exploring a grassy trail" fetchPriority="high"/><div className="photo-label">OUTSIDE IS THEIR HAPPY PLACE.</div><div className="sticker">VERY<br/>GOOD<br/>DOGS ↗</div></div></section>
<div className="ticker" aria-hidden="true">FRESH AIR <span>✳</span> NEW FRIENDS <span>✳</span> BIG SNIFFS <span>✳</span> GOOD DAYS <span>✳</span> FRESH AIR <span>✳</span></div>
<section id="walks" className="section"><div className="section-heading"><div><span className="eyebrow">01 / PICK THEIR ADVENTURE</span><h2>A good day starts<br/>with a good walk.</h2></div><p>Every dog has their own pace.<br/>Let’s find the one that suits yours.</p></div><div className="cards">{site.services.map((s,i)=><article className="service" key={s.id}><div className="service-photo"><img src={asset(s.image)} width={s.image==="ride.jpg"?400:360} height={s.image==="ride.jpg"?385:450} alt={s.type==="Home visits"?"Dog wearing sunglasses, enjoying the breeze":"Dogs enjoying the outdoors"} loading="lazy"/><span className="service-tag">0{i+1} / {s.type}</span></div><div className="service-copy"><h3>{s.name}</h3><p>{s.description}</p><div className="service-meta"><span>{s.duration}</span><span>{s.price}</span></div><a href="#join">Tell us what they need <span>↗</span></a></div></article>)}</div></section>
<section id="about" className="about"><div className="about-photo"><img src={asset("trail.jpg")} width={360} height={450} alt="Dog bounding down a trail carrying a stick" loading="lazy"/><span className="caption">LESS SCROLLING. MORE STROLLING.</span></div><div className="about-copy"><span className="eyebrow">02 / GOOD PEOPLE. GOOD DOGS.</span><h2>Small business.<br/>Big dog energy.</h2><p>{site.intro}</p><div className="values"><div><span>↗</span><h3>Dog first. Always.</h3><p>We start with their personality, pace and comfort.</p></div><div><span>✳</span><h3>A familiar face.</h3><p>Get to know who’s holding the other end of the lead.</p></div><div><span>♡</span><h3>Let’s talk it through.</h3><p>Discuss routines, handling and expectations before the first walk.</p></div></div><a className="text-link" href="#join">Meet your next walking buddy ↗</a></div></section>
<section className="section process"><span className="eyebrow">03 / FROM HELLO TO LET’S GO</span><h2>Three steps.<br/>A whole lot of tail wags.</h2><div className="steps">{[["01","Tell us about your dog","Their quirks, their routine and their favourite kind of day."],["02","Have a proper hello","We’ll arrange a meet-and-greet and chat about the right fit."],["03","Make room for adventure","Agree your walking routine, then let the good days begin."]].map(([n,t,d])=><div key={n}><span>{n} ↗</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section id="faq" className="section faq"><div><span className="eyebrow">04 / GOOD QUESTIONS</span><h2>A few things<br/>you might wonder.</h2></div><div>{[["Where do you walk?",`Service area: ${site.area}. Send your postcode and we’ll confirm whether we can cover your address.`],["Will my dog suit a group walk?","We’ll discuss temperament, handling and comfort at the meet-and-greet. If company isn’t their thing, ask about solo walks."],["Can I book a regular routine?","Tell us your preferred days and times. We’ll confirm availability and pricing before agreeing any bookings."],["What about rain, heat or cancellations?","We’ll agree weather arrangements, safety considerations and cancellation terms with you before the first booking."],["Is this an instant booking?","No. The form sends an enquiry so we can discuss your dog’s needs and confirm availability together."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section id="join" className="join"><div><span className="eyebrow">05 / THERE’S A GOOD DAY OUT THERE</span><h2>Let’s make<br/>their day.</h2><p>Tell us a little about your best friend.<br/>We’ll take it from there.</p><div className="join-mark">✳</div></div><EnquiryForm/></section></main>
<footer><img className="footer-logo" src="/images/logo.png" alt="Goodboys"/><div><span>GOOD WALKS. GREAT DOGS.</span><a href="/privacy">Privacy</a>{site.email&&<a href={`mailto:${site.email}`}>Get in touch ↗</a>}<span>© {new Date().getFullYear()} Goodboys</span></div></footer></>; }
