"use client";
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import type {Enquiry,Client,Walk,Reply} from '@/lib/os-types';
import {dayKey,overview} from '@/lib/os-data.mjs';
import Analytics from '@/components/Analytics';
type Tab='Today'|'Enquiries'|'Calendar'|'Clients'|'Analytics';
const serviceLabel=(value:string)=>value==='group'?'Group walk':value==='visit'?'Home visit':'Previously booked service';
const currency=process.env.NEXT_PUBLIC_BUSINESS_CURRENCY||'GBP';
const money=(v:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(v);
const time=(s:string)=>new Date(s).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const localInput=(s:string)=>{const d=new Date(s);return `${dayKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
export default function OS(){
 const db=useMemo(()=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createClient(url,key):null;},[]);
 const [ready,setReady]=useState(false),[signed,setSigned]=useState(false),[tab,setTab]=useState<Tab>('Today'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const [enquiries,setEnquiries]=useState<Enquiry[]>([]),[clients,setClients]=useState<Client[]>([]),[walks,setWalks]=useState<Walk[]>([]),[replies,setReplies]=useState<Reply[]>([]);
 const [selected,setSelected]=useState<Enquiry|null>(null),[clientEdit,setClientEdit]=useState<Partial<Client>|null>(null),[walkEdit,setWalkEdit]=useState<Partial<Walk>|null>(null);
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('open'),[date,setDate]=useState(dayKey(new Date())),[month,setMonth]=useState(dayKey(new Date()).slice(0,7));
 const stats=overview(enquiries,clients,walks);
 useEffect(()=>{if(!selected&&!clientEdit&&!walkEdit)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('.os-dialog');const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const focusables=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,textarea,[tabindex="0"]')||[]);focusables()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){setSelected(null);setClientEdit(null);setWalkEdit(null);}if(e.key==='Tab'){const items=focusables(),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=oldOverflow;document.removeEventListener('keydown',key);previous?.focus();};},[selected?.id,!!clientEdit,!!walkEdit,busy]);

 async function load(){if(!db)return;setLoading(true);const results=await Promise.all([db.from('enquiries').select('*').order('created_at',{ascending:false}),db.from('clients').select('*').order('name'),db.from('walks').select('*').order('starts_at'),db.from('enquiry_replies').select('*').order('created_at',{ascending:false})]);setLoading(false);if(results.some(r=>r.error)){setError('Could not load records. Check the connection and OS database setup.');return;}setEnquiries(results[0].data||[]);setClients(results[1].data||[]);setWalks(results[2].data||[]);setReplies(results[3].data||[]);}
 useEffect(()=>{if(!db){setReady(true);return;}const check=async()=>{const {data:{session}}=await db.auth.getSession();if(session){const {data,error}=await db.from('os_owners').select('user_id').eq('user_id',session.user.id).maybeSingle();if(data&&!error){setSigned(true);await load();}else{setSigned(false);setError('This account has no owner access. Add its user ID to os_owners in Supabase.');}}else{setSigned(false);setEnquiries([]);setClients([]);setWalks([]);setReplies([]);setSelected(null);setClientEdit(null);setWalkEdit(null);}setReady(true);};void check();const {data:{subscription}}=db.auth.onAuthStateChange(()=>{setTimeout(()=>void check(),0);});return()=>subscription.unsubscribe();},[db]);
 useEffect(()=>{if(!signed)return;const refresh=()=>void load();window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh);},[signed]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:'Could not save. Try again.');}finally{setBusy(false);}}
 async function saveEnquiry(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||!db)return;const f=new FormData(e.currentTarget);await action(async()=>{const update={status:String(f.get('status')),internal_notes:String(f.get('internal_notes')),follow_up_on:f.get('follow_up_on')||null};const {error}=await db.from('enquiries').update(update).eq('id',selected.id);if(error)throw error;setSelected({...selected,...update} as Enquiry);});}
 async function saveClient(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!db)return;const f=new FormData(e.currentTarget);await action(async()=>{const payload={name:String(f.get('name')).trim(),email:String(f.get('email')).trim(),dog:String(f.get('dog')).trim(),phone:String(f.get('phone')),address:String(f.get('address')),care_notes:String(f.get('care_notes')),active:f.get('active')==='on'};const result=clientEdit?.id?await db.from('clients').update(payload).eq('id',clientEdit.id):await db.from('clients').insert(payload);if(result.error)throw result.error;setClientEdit(null);});}
 async function saveWalk(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!db)return;const f=new FormData(e.currentTarget);await action(async()=>{const start=new Date(String(f.get('starts_at')));const duration=Number(f.get('duration'));const clientId=String(f.get('client_id'));const end=start.getTime()+duration*60000;const overlap=walks.some(w=>w.id!==walkEdit?.id&&w.client_id===clientId&&w.status!=='cancelled'&&start.getTime()<new Date(w.starts_at).getTime()+w.duration*60000&&end>new Date(w.starts_at).getTime());if(overlap)throw new Error('This dog already has a walk at that time.');const payload={client_id:clientId,starts_at:start.toISOString(),duration,service:String(f.get('service')),fee:Number(f.get('fee')),status:String(f.get('status')),paid:f.get('paid')==='on',notes:String(f.get('notes'))};const result=walkEdit?.id?await db.from('walks').update(payload).eq('id',walkEdit.id):await db.from('walks').insert(payload);if(result.error)throw result.error;setWalkEdit(null);});}
 async function sendReply(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!db||!selected)return;const form=e.currentTarget,body=String(new FormData(form).get('body'));await action(async()=>{const {data:{session}}=await db.auth.getSession();const response=await fetch('/api/os/reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({enquiry_id:selected.id,body})});const result=await response.json();if(!response.ok)throw new Error(result.error);setSelected({...selected,status:'contacted'});form.reset();if(result.warning)setError(result.warning);});}
 const clientName=(id:string)=>{const c=clients.find(c=>c.id===id);return c?`${c.dog} · ${c.name}`:'Client unavailable';};
 function walkList(items:Walk[]){return items.length?<div className="os-list">{items.map(w=><button key={w.id} className="os-row" onClick={()=>setWalkEdit(w)}><span className="os-time">{time(w.starts_at)}</span><span><strong>{clientName(w.client_id)}</strong><small>{serviceLabel(w.service)} · {w.duration} min · {money(Number(w.fee))}</small></span><span className={`os-pill ${w.status}`}>{w.status}{w.paid?' · paid':''}</span></button>)}</div>:<div className="os-empty">No walks here yet. A little room for adventure.</div>;}
 if(!ready)return <div className="os-login">Opening Goodboys…</div>;
 if(!signed)return <main className="os-login"><img src="/images/logo.png" alt="Goodboys"/><span className="eyebrow">YOUR BUSINESS, ORGANISED.</span><h1>A good day<br/>starts here.</h1>{!db?<div className="os-notice">Connect Supabase to open your OS. Follow OS-SETUP.md, add the two public Supabase variables, and redeploy.</div>:<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');const {error}=await db.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});setBusy(false);if(error)setError(error.message);}}><label>Email<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="button" disabled={busy}>{busy?'Signing in…':'Open my OS ↗'}</button></form>}{error&&<p role="alert">{error}</p>}<p className="os-muted">Private owner workspace · <a href="/">Public website ↗</a></p></main>;
 const followups=enquiries.filter(e=>e.status!=='closed'&&e.follow_up_on&&e.follow_up_on<=dayKey(new Date()));
 const days=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();const offset=(new Date(`${month}-01T12:00:00`).getDay()+6)%7;
 return <div className="os-shell"><aside className="os-sidebar"><img src="/images/logo.png" alt="Goodboys"/><span className="eyebrow">THE EVERYDAY OS</span><nav aria-label="OS sections">{(['Today','Enquiries','Calendar','Clients','Analytics'] as Tab[]).map((t,i)=><button key={t} aria-current={tab===t?'page':undefined} className={tab===t?'active':''} onClick={()=>{setTab(t);setSearch('');}}><span>{['✳','↗','▦','♡','▥'][i]}</span>{t}{t==='Enquiries'&&stats.newEnquiries>0&&<b>{stats.newEnquiries}</b>}</button>)}</nav><a href="/">View website ↗</a><button onClick={()=>void db?.auth.signOut()}>Sign out</button></aside>
 <main className="os-main"><div className="os-top"><div><span className="eyebrow">GOODBOYS / {tab.toUpperCase()}</span><h1>{tab==='Today'?'Here’s your good day.':tab==='Enquiries'?'New friends start here.':tab==='Calendar'?'Room for adventure.':tab==='Analytics'?'See how things are growing.':'Your people & their dogs.'}</h1></div><button className="os-secondary" disabled={loading||busy} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh ↻'}</button></div>{error&&<div className="os-notice" role="alert">{error}<button aria-label="Dismiss notice" onClick={()=>setError('')}>×</button></div>}
 {tab==='Today'&&<><div className="os-metrics">{[[stats.newEnquiries,'New enquiries'],[stats.today.length,'Walks today'],[stats.activeClients,'Active clients'],[money(stats.earned),'Completed walk fees · this month']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><div className="os-columns"><section className="os-panel"><div className="os-heading"><h2>Today’s walks</h2><button className="os-secondary" onClick={()=>setWalkEdit({starts_at:`${date}T09:00:00`,duration:60,fee:0,status:'scheduled',service:'group'})}>+ Add walk</button></div>{walkList(stats.today)}<p className="os-muted">Times use your device timezone.</p></section><section className="os-panel"><h2>Needs a little attention</h2>{followups.length?followups.map(e=><button className="os-row" key={e.id} onClick={()=>{setTab('Enquiries');setSelected(e);}}><span><strong>{e.dog} · {e.name}</strong><small>Follow up {e.follow_up_on}</small></span><span>↗</span></button>):<p className="os-muted">No follow-ups due. You’re up to date.</p>}<hr/><p><strong>{money(stats.unpaid)}</strong> unpaid completed walk fees</p><p className="os-muted">{stats.completed} walks completed this month. Figures come from your walk records, not bank transactions.</p><button className="os-secondary" onClick={()=>setTab('Enquiries')}>Open enquiry inbox ↗</button></section></div></>}
 {tab==='Enquiries'&&<><div className="os-toolbar"><input aria-label="Search enquiries" placeholder="Search dog, owner or email…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Enquiry status filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open enquiries</option><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option><option value="all">All</option></select></div><section className="os-panel">{enquiries.filter(e=>(filter==='all'||filter==='open'&&e.status!=='closed'||e.status===filter)&&`${e.name} ${e.dog} ${e.email}`.toLowerCase().includes(search.toLowerCase())).map(e=><button className="os-row" key={e.id} onClick={()=>setSelected(e)}><span className="os-avatar">{e.dog.slice(0,1)}</span><span><strong>{e.dog} · {e.name}</strong><small>{serviceLabel(e.service)} · {e.postcode} · {new Date(e.created_at).toLocaleDateString()}</small>{e.follow_up_on&&<small>Follow up: {e.follow_up_on}</small>}</span><span className={`os-pill ${e.status}`}>{e.status}</span></button>)}{!enquiries.length&&<div className="os-empty">Website enquiries will arrive here automatically.</div>}</section></>}
 {tab==='Calendar'&&<><div className="os-toolbar"><label>Month<input type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setDate(`${e.target.value}-01`);}}}/></label><button className="button" onClick={()=>setWalkEdit({starts_at:`${date}T09:00:00`,duration:60,fee:0,status:'scheduled',service:'group'})}>+ Add walk</button></div><section className="os-panel"><div className="os-calendar">{['M','T','W','T','F','S','S'].map((d,i)=><span className="os-weekday" key={i}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={`pad${i}`}/>)}{Array.from({length:days},(_,i)=>{const d=`${month}-${String(i+1).padStart(2,'0')}`,count=walks.filter(w=>dayKey(w.starts_at)===d&&w.status!=='cancelled').length;return <button className={date===d?'chosen':''} key={d} aria-label={`${d}, ${count} walks`} aria-pressed={date===d} onClick={()=>setDate(d)}>{i+1}{count>0&&<small>{count} <span>walk{count===1?'':'s'}</span></small>}</button>;})}</div></section><section className="os-panel"><h2>{new Date(`${date}T12:00:00`).toLocaleDateString([],{weekday:'long',day:'numeric',month:'long'})}</h2>{walkList(walks.filter(w=>dayKey(w.starts_at)===date))}</section></>}
 {tab==='Clients'&&<><div className="os-toolbar"><input aria-label="Search clients" value={search} placeholder="Search owners & dogs…" onChange={e=>setSearch(e.target.value)}/><button className="button" onClick={()=>setClientEdit({active:true})}>+ Add client</button></div><section className="os-panel">{clients.filter(c=>`${c.name} ${c.dog} ${c.email}`.toLowerCase().includes(search.toLowerCase())).map(c=><button className="os-row" key={c.id} onClick={()=>setClientEdit(c)}><span className="os-avatar">{c.dog.slice(0,1)}</span><span><strong>{c.dog} · {c.name}</strong><small>{c.email||'No email saved'}{c.phone?` · ${c.phone}`:''}</small></span><span className="os-pill">{c.active?'Active':'Archived'}</span></button>)}{!clients.length&&<div className="os-empty">Add your first client or convert an enquiry.</div>}</section></>}
 {tab==='Analytics'&&<Analytics enquiries={enquiries} clients={clients} walks={walks}/>}
 <p className="os-footnote">Keep it simple. Keep it good. · Online connection required.</p></main>
 {selected&&<div className="os-overlay"><section className="os-dialog" role="dialog" aria-modal="true" aria-labelledby="enquiry-title"><button disabled={busy} className="os-close" aria-label="Close enquiry" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">ENQUIRY / {selected.status.toUpperCase()}</span><h2 id="enquiry-title">{selected.dog} & {selected.name}</h2><p>{selected.email} · {selected.postcode}</p><div className="os-message">{selected.notes||'No extra notes submitted.'}</div>{error&&<div className="os-notice" role="alert">{error}</div>}<form onSubmit={saveEnquiry}><div className="os-form-grid"><label>Status<select name="status" defaultValue={selected.status}><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></label><label>Follow-up date<input name="follow_up_on" type="date" defaultValue={selected.follow_up_on||''}/></label></div><label>Private notes<textarea name="internal_notes" defaultValue={selected.internal_notes} maxLength={5000} rows={3}/></label><button className="os-secondary" disabled={busy}>Save follow-up</button></form><div className="os-actions"><a className="os-secondary" href={`mailto:${encodeURIComponent(selected.email)}?subject=${encodeURIComponent('Goodboys — '+selected.dog)}`}>Open email ↗</a><button className="os-secondary" disabled={busy||!!selected.client_id} onClick={()=>void action(async()=>{const {data,error}=await db!.rpc('convert_enquiry',{enquiry_uuid:selected.id});if(error)throw error;setSelected({...selected,client_id:data,status:'closed'});})}>{selected.client_id?'Added to clients ✓':'Add to clients ↗'}</button></div><h3>Reply from Goodboys</h3><p className="os-muted">Send via your connected email service. Customer replies go to your business inbox.</p><form onSubmit={sendReply}><label>Message<textarea name="body" required maxLength={5000} rows={5} placeholder={`Hi ${selected.name}, thanks for getting in touch about ${selected.dog}…`}/></label><button className="button" disabled={busy}>{busy?'Working…':'Send reply ↗'}</button></form>{replies.filter(r=>r.enquiry_id===selected.id).map(r=><div className="os-message" key={r.id}><small>Sent {new Date(r.created_at).toLocaleString()}</small><p>{r.body}</p></div>)}</section></div>}
 {clientEdit&&<div className="os-overlay"><section className="os-dialog" role="dialog" aria-modal="true" aria-labelledby="client-title"><button disabled={busy} className="os-close" aria-label="Close client" onClick={()=>setClientEdit(null)}>×</button><h2 id="client-title">{clientEdit.id?'Client & dog':'A new good friend'}</h2>{error&&<div className="os-notice" role="alert">{error}</div>}<form onSubmit={saveClient}><div className="os-form-grid"><label>Owner name<input name="name" required maxLength={100} defaultValue={clientEdit.name}/></label><label>Dog name<input name="dog" required maxLength={100} defaultValue={clientEdit.dog}/></label><label>Email<input name="email" type="email" maxLength={254} defaultValue={clientEdit.email}/></label><label>Phone<input name="phone" type="tel" maxLength={40} defaultValue={clientEdit.phone}/></label></div><label>Address / pickup details<textarea name="address" maxLength={1000} defaultValue={clientEdit.address}/></label><label>Care notes<textarea name="care_notes" maxLength={5000} rows={4} placeholder="Temperament, handling, emergency contact…" defaultValue={clientEdit.care_notes}/></label><label className="os-checkbox"><input name="active" type="checkbox" defaultChecked={clientEdit.active}/>Active client</label><button className="button" disabled={busy}>Save client</button></form>{clientEdit.id&&<><h3>Recent & upcoming walks</h3>{walkList(walks.filter(w=>w.client_id===clientEdit.id).slice(-10))}<button className="os-secondary" onClick={()=>{setWalkEdit({client_id:clientEdit.id,starts_at:`${date}T09:00:00`,duration:60,fee:0,status:'scheduled',service:'group'});setClientEdit(null);}}>Schedule a walk ↗</button></>}</section></div>}
 {walkEdit&&<div className="os-overlay"><section className="os-dialog" role="dialog" aria-modal="true" aria-labelledby="walk-title"><button disabled={busy} className="os-close" aria-label="Close walk" onClick={()=>setWalkEdit(null)}>×</button><h2 id="walk-title">{walkEdit.id?'Walk details':'Plan a good walk'}</h2>{!clients.length?<p>Add a client first, then schedule their walk.</p>:<form onSubmit={saveWalk}>{error&&<div className="os-notice" role="alert">{error}</div>}<label>Client & dog<select name="client_id" required defaultValue={walkEdit.client_id||''}><option disabled value="">Choose a dog</option>{clients.filter(c=>c.active||c.id===walkEdit.client_id).map(c=><option key={c.id} value={c.id}>{c.dog} · {c.name}</option>)}</select></label><div className="os-form-grid"><label>Starts (device timezone)<input name="starts_at" type="datetime-local" required defaultValue={walkEdit.starts_at?localInput(walkEdit.starts_at):''}/></label><label>Minutes<input name="duration" type="number" required min={5} max={480} defaultValue={walkEdit.duration||60}/></label><label>Service<select name="service" defaultValue={walkEdit.service||'group'}><option value="group">Group walk</option>{walkEdit.id&&walkEdit.service==='solo'&&<option value="solo">Previously booked service</option>}<option value="visit">Home visit</option></select></label><label>Fee ({currency})<input name="fee" type="number" min={0} max={9999999} step="0.01" required defaultValue={walkEdit.fee||0}/></label></div><label>Status<select name="status" defaultValue={walkEdit.status||'scheduled'}><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className="os-checkbox"><input name="paid" type="checkbox" defaultChecked={walkEdit.paid}/>Payment received</label><label>Walk notes<textarea name="notes" maxLength={5000} defaultValue={walkEdit.notes}/></label><button className="button" disabled={busy}>Save walk</button><p className="os-muted">One booking per dog. Dogs in a group can share a time.</p></form>}</section></div>}
 </div>;
}
